/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FrOUlFAWwe3
 */
import { Label } from "@/components/ui/label"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function Details() {
  return (
    <div className="space-y-6">
      <div className="border-t border-b border-gray-200 py-6 grid gap-4 md:grid-cols-2 items-center md:gap-6 lg:gap-12 xl:gap-16 border-gray-200 dark:border-gray-800">
        <div className="space-y-2 md:order-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">2023 Porsche 911 Carrera 4S</h1>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-0.5">
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
            </div>
          </div>
        </div>
        <div className="grid gap-2 md:order-1">
          <div className="text-4xl font-bold">$149</div>
          <div className="text-sm md:text-base text-gray-500 dark:text-gray-400">Per day</div>
        </div>
      </div>
      <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl mx-auto px-4">
        <div className="grid md:grid-cols-5 gap-3 items-start">
          <div className="hidden md:flex flex-col gap-3 items-start">
            <button className="border hover:border-gray-900 rounded-lg overflow-hidden transition-colors dark:hover:border-gray-50">
              <img
                alt="Preview thumbnail"
                className="aspect-[5/6] object-cover"
                height={120}
                src="/placeholder.svg"
                width={100}
              />
              <span className="sr-only">View Image 1</span>
            </button>
            <button className="border hover:border-gray-900 rounded-lg overflow-hidden transition-colors dark:hover:border-gray-50">
              <img
                alt="Preview thumbnail"
                className="aspect-[5/6] object-cover"
                height={120}
                src="/placeholder.svg"
                width={100}
              />
              <span className="sr-only">View Image 3</span>
            </button>
            <button className="border hover:border-gray-900 rounded-lg overflow-hidden transition-colors dark:hover:border-gray-50">
              <img
                alt="Preview thumbnail"
                className="aspect-[5/6] object-cover"
                height={120}
                src="/placeholder.svg"
                width={100}
              />
              <span className="sr-only">View Image 4</span>
            </button>
            <button className="border hover:border-gray-900 rounded-lg overflow-hidden transition-colors dark:hover:border-gray-50">
              <img
                alt="Preview thumbnail"
                className="aspect-[5/6] object-cover"
                height={120}
                src="/placeholder.svg"
                width={100}
              />
              <span className="sr-only">View Image 4</span>
            </button>
          </div>
          <div className="md:col-span-4">
            <img
              alt="Product Image"
              className="aspect-[2/3] object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
              height={900}
              src="/placeholder.svg"
              width={600}
            />
          </div>
        </div>
        <div className="grid gap-4 md:gap-10 items-start">
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="color">
              Color
            </Label>
            <RadioGroup className="flex items-center gap-2" defaultValue="black" id="color">
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="color-black"
              >
                <RadioGroupItem id="color-black" value="black" />
                Black
              </Label>
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="color-white"
              >
                <RadioGroupItem id="color-white" value="white" />
                White
              </Label>
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="color-blue"
              >
                <RadioGroupItem id="color-blue" value="blue" />
                Blue
              </Label>
            </RadioGroup>
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="size">
              Size
            </Label>
            <RadioGroup className="flex items-center gap-2" defaultValue="m" id="size">
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="size-xs"
              >
                <RadioGroupItem id="size-xs" value="xs" />
                XS
              </Label>
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="size-s"
              >
                <RadioGroupItem id="size-s" value="s" />
                S{"\n                          "}
              </Label>
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="size-m"
              >
                <RadioGroupItem id="size-m" value="m" />
                M{"\n                          "}
              </Label>
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="size-l"
              >
                <RadioGroupItem id="size-l" value="l" />
                L{"\n                          "}
              </Label>
              <Label
                className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                htmlFor="size-xl"
              >
                <RadioGroupItem id="size-xl" value="xl" />
                XL
              </Label>
            </RadioGroup>
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="quantity">
              Quantity
            </Label>
            <Select defaultValue="1">
              <SelectTrigger className="w-24">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1</SelectItem>
                <SelectItem value="2">2</SelectItem>
                <SelectItem value="3">3</SelectItem>
                <SelectItem value="4">4</SelectItem>
                <SelectItem value="5">5</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Button size="lg">Rent Now</Button>
        </div>
      </div>
      <div className="grid gap-6 lg:gap-12 max-w-6xl mx-auto px-4">
        <div className="grid gap-4">
          <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">About the 2023 Porsche 911 Carrera 4S</h3>
          <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            The Porsche 911 Carrera 4S is a sports car that offers a perfect blend of performance and luxury. It is
            powered by a 3.0-liter twin-turbocharged flat-six engine that produces 443 horsepower and 390 lb-ft of
            torque. The engine is mated to an 8-speed PDK transmission, which allows the 911 Carrera 4S to accelerate
            from 0 to 60 mph in just 3.4 seconds and reach a top speed of 190 mph.
          </p>
        </div>
        <div className="grid gap-4">
          <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">Features & Specifications</h3>
          <dl className="grid gap-2 md:grid-cols-2">
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">Engine Type</dt>
              <dd>3.0L Twin-Turbocharged Flat-6</dd>
            </div>
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">Horsepower</dt>
              <dd>443 @ 6,500 rpm</dd>
            </div>
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">Torque</dt>
              <dd>390 lb-ft @ 2,300-5,000 rpm</dd>
            </div>
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">0-60 mph</dt>
              <dd>3.4 seconds</dd>
            </div>
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">Top Speed</dt>
              <dd>190 mph</dd>
            </div>
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">Transmission</dt>
              <dd>8-speed PDK</dd>
            </div>
            <div className="flex items-start gap-2">
              <dt className="min-w-[150px] font-semibold">Fuel Efficiency</dt>
              <dd>City: 18 mpg, Highway: 25 mpg</dd>
            </div>
          </dl>
        </div>
      </div>
    </div>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
